### PR TITLE
Better branch prediction

### PR DESCRIPTION
**Pull request by i-am-a-teapot**
This version of setlow and high was a bit faster for me, (profile guided) not sure if this holds with error bars though

### CODE REVIEW

**Comment by i-am-a-teapot** [comment]
Sorry for abusing the same branch

**Comment by Swarsel** [comment]
Averaged over 100 runs I get this runtime:
0.933525 +- 0.000959 seconds time elapsed  ( +-  0.10% )

So error bars seem ok, not sure if this is actually faster however?
My runtimes on main (https://github.com/Swarsel/MagicHexagon/commit/a060402984a4b6d60a2553113c2c4e92587f2495) yield (averaged over 100 runs):
0.800973 +- 0.000836 seconds time elapsed ( +- 0.10% )

Not sure however if I am missing something, your runtime in  #7 was also a lot faster than mine (0.935466117 for me), I ran this from a clean clone however, so I dont know

**Comment by i-am-a-teapot** [comment]
@Swarsel did you compile with profile guided optimitazion? 
Also see https://github.com/Swarsel/MagicHexagon/pull/5

**Comment by Swarsel** [comment]
Yep, but maybe I am using it wrong?

EDIT: to be used this way
- change BUILD := profile in Makefile
- make
- make measure
- change BUILD := release in Makefile
- make clean
- make
- run again

**Comment by i-am-a-teapot** [comment]
make clean inbetween to get new files?
I get 0.73 in main

**Comment by Swarsel** [comment]
Ah yes, it was due to my own incompetence :p
Now I get over 100 runs
0.704476 +- 0.000717 seconds time elapsed  ( +-  0.10% )

**Review by Swarsel — APPROVED** [review]

**Pull request merged**
